server:
  host: ""
  port: 6021

redis:
  address: "localhost:6379"
  password: ""
  db: 0

database:
  driver: "postgresql"
  host: "localhost"
  port: "5432"
  user: "user"
  password: "mysecretpassword"
  db_name: "kenalan"